import { Forfait } from './forfait';

export const forfaits : Forfait [] = [
    
    {
        _id: '1',
        destination: 'Rio de Janeiro, Brésil',
        villeDepart: 'Québec',
        hotel: 
            {
                nom: 'Belmont Copacabana Palace',
                coordonnees: 'R. Domingos Ferreira, 242 - Copacabana, Rio de Janeiro - RJ, 22050-012, Brasil',
                nombreEtoiles: 5,
                nombreChambres: 100,
                caracteristiques: [ "Face à la plage",
                                    "Spa",
                                    "Piscine",
                                    "Haute cuisine",
                                    "Garderie 24h", 
                                    "6 restaurants",
                                    "Randonnée Serra do Mar",
                                    "Centre fitness",
                                    "Excursion Baya de Angra",
                                    "WiFi: tout le complex"],
            },
        prix: 5600,
        rabais: 500,
        dateDepart: '2021-02-19',
        dateRetour: '2021-03-07',        
        vedette: true,
        duree: '15 jours',
        da: '1996489',
    },
    {
        _id: '2',
        destination: 'Angra dos Reis, Brésil',
        villeDepart: 'Montréal',
        hotel: {
            nom: 'Fasano Angra dos Reis',
            coordonnees: 'Rod. Gov. Mário Covas, Km 512 - Porto Frade, Angra dos Reis - RJ, 23946-017, Brasil',
            nombreEtoiles: 4,
            nombreChambres: 40,
            caracteristiques: [ "Face à la plage",
                                "Spa",
                                "Piscine",
                                "Haute cuisine",
                                "Garderie 24h", 
                                "6 restaurants",
                                "Randonnée Serra do Mar",
                                "Centre fitness",
                                "Excursion Baya de Angra",
                                "WiFi: tout le complex"], 
        },
        prix: 2000,
        rabais: 0,
        dateDepart: '2021-02-19',
        dateRetour: '2021-03-07',        
        vedette: false,
        duree: '15 jours',
        da: '1996489',
    },
    {
        _id: '3',
        destination: 'Rio de Janeiro, Brésil',
        villeDepart:'Québec',
        hotel: {
            nom: 'Fasano Rio de Janeiro',
            coordonnees: 'Av. Vieira Souto, 80 - Ipanema, Rio de Janeiro - RJ, 22420-002, Brasil',
            nombreEtoiles: 5,
            nombreChambres: 100,
            caracteristiques: [ "Face à la plage",
                                "Spa Fasano",
                                "Piscine rooftop",
                                "Haute cuisine",
                                "Garderie 24h", 
                                "3 restaurants",
                                "Randonnée Serra do Mar",
                                "Centre fitness",
                                "Excursion Rio",
                                "WiFi: tout le complex"], 
        },
        prix: 2000,
        rabais: 400,
        dateDepart: '2021-02-19',
        dateRetour: '2021-03-07',        
        vedette: true,
        duree: '15 jours',
        da: '1996489',
    },
    {
        _id: '4',
        destination: 'Salvador, Brésil',
        villeDepart: 'Québec',
        hotel: {
            nom: 'Fasano Salvador',
            coordonnees: 'Praça Castro Alves, 5 - Centro, Salvador - BA, 40020-160, Brasil',
            nombreEtoiles: 5,
            nombreChambres: 60,
            caracteristiques: [ "Face à la baie",
                                "Spa Fasano",
                                "Piscine rooftop",
                                "Haute cuisine",
                                "Garderie 24h", 
                                "2 restaurants",
                                "Excursion Vieux Salvador",
                                "Excursion Baia de todos os Santos",
                                "WiFi: tout le complex"], 
        },
        prix: 2000,
        rabais: 0,
        dateDepart: '2021-02-19',
        dateRetour: '2021-03-07',        
        vedette: false,
        duree: '15 jours',
        da: '1996489',
    },
    {
        _id: '5',
        destination: 'Archipel Fernando de Noronha, Brésil',
        villeDepart: 'Montreal',
        hotel: {
            nom: 'Parc National Hotel ',
            coordonnees: 'Porto dos Pescadores, Fernaldo de Noronha, Brasil',
            nombreEtoiles: 3,
            nombreChambres: 15,
            caracteristiques: [ "Face à la plage", 
                                "2 restaurants",
                                "Excursion caïac",
                                "Randonée parc national",
                                "Plongée sous-marine",
                                "Pas de wifi"], 
        },
        prix: 2000,
        rabais: 500,
        dateDepart: '2021-02-19',
        dateRetour: '2021-03-07',        
        vedette: true,
        duree: '15 jours',
        da: '1996489',
    },
    {
        _id: '6',
        destination: 'Barra de Sao Miguel, Ceara, Brésil',
        villeDepart: 'Québec',
        hotel: {
            nom: 'Kenoa Resort',
            coordonnees: 'R. Escritor Jorge de Lima, 58 - Barra Mar, Barra de São Miguel - AL, 57180-000, Brasil',
            nombreEtoiles: 5,
            nombreChambres: 60,
            caracteristiques: [ "Face à la plage",
                                "Spa",
                                "Piscine privée",
                                "Haute cuisine",
                                "Garderie 24h", 
                                "7 restaurants",
                                "Centre fitness",
                                "Plongée sous-marine",
                                "Excursion boat experience",
                                "WiFi: tout le complex"], 
        },
        prix: 6000,
        rabais: 0,
        dateDepart: '2021-02-19',
        dateRetour: '2021-03-07',       
        vedette: false,
        duree: '15 jours',
        da: '1996489',
    },
    {
        _id: '7',
        destination: 'Itacaré, Brésil',
        villeDepart: 'Québec',
        hotel: {
            nom: 'Txai Resorts',
            coordonnees: 'R. Escritor Jorge de Lima, 58 - Barra Mar, Barra de São Miguel - AL, 57180-000, Brasil',
            nombreEtoiles: 4,
            nombreChambres: 60,
            caracteristiques: [ "Face à la plage",
                                "Spa shamash",
                                "Piscine",
                                "Haute cuisine",
                                "Garderie",
                                "Miniclub", 
                                "3 restaurants",
                                "Excursion boat experience",
                                "WiFi: tout le complex"], 
        },
        prix: 3000,
        rabais: 0,
        dateDepart: '2021-02-19',
        dateRetour: '2021-03-07',        
        vedette: false,
        duree: '15 jours',
        da: '1996489',
    },
    {
        _id: '8',
        destination: 'Rio de Janeiro, Brésil',
        villeDepart: 'Québec',
        hotel: {
            nom: 'Fairmont Copacabana Rio',
            coordonnees: 'Av. Atlântica, 4240 - Copacabana, Rio de Janeiro - RJ, 22070-002, Brasil',
            nombreEtoiles: 5,
            nombreChambres: 100,
            caracteristiques: [ "Face à la plage",
                                "Spa shamash",
                                "Piscine",
                                "Haute cuisine",
                                "Baby-sitter",
                                "Miniclub", 
                                "3 restaurants",
                                "2 bars",
                                "Chauffeur",
                                "Excursion Rio marin"], 
        },
        prix: 4000,
        rabais: 0,
        dateDepart: '2021-02-19',
        dateRetour: '2021-03-07',        
        vedette: false,
        duree: '15 jours',
        da: '1996489',
    },
];
